'use client'
import { useState, useRef, useEffect } from 'react'
import DashboardHeader from '@/components/layout/DashboardHeader'

const AI_RESPONSES: [string, string][] = [
  ['expense', '📊 Expense Analysis\n\nExpenses increased 8.7% last quarter:\n• Payroll (+12%) — 2 engineering hires: +$56K\n• Marketing (+24%) — Q4 campaign: +$38K, CAC improved $2,840→$2,210\n• Infrastructure (+18%) — Reserved instances save $43K/yr\n\nExpense:Revenue ratio improved 71.2%→70.8%. No corrective action needed.'],
  ['forecast', '🔮 Revenue Forecast — Prophet + XGBoost\n\nQ1 Projection: $3.20M (+12.7%)\n\n• Bull Case (28%): $3.89M\n• Base Case (54%): $3.20M  \n• Bear Case (18%): $2.93M\n\nModel accuracy: 94.7% | CI: ±$280K at 89%'],
  ['health', '💚 Financial Health Index: 87/100\n\n• Stability (91%): 18.4mo runway, positive FCF\n• Efficiency (84%): 72.3% gross margin\n• Risk (76%): 3 anomalies, concentration risk\n• Forecast (88%): 94.7% model accuracy'],
  ['anomal', '🛡️ Anomaly Detection Results\n\n🔴 TXN-4821 — $12,800 | 340% above baseline | ACTION: Hold\n🟡 INV-DUP-092 — $3,200 duplicate | Already held\n🟡 VENDOR-GHK — $1,200 recovery opportunity\n\nTotal exposure: $16,000 | Recoverable: $4,400'],
  ['report', '📋 Executive Summary — November 2024\n\nRevenue: $318K (+10.4% MoM) | TTM: $2.84M\nCash: $2.1M | Runway: 18.4 months | FCF: Positive\n\nAI Alerts: 3 anomalies ($16K)\nOutlook: Q1 base case $3.2M. Growth intact.\n\nGenerated by FinFlow AI · LangChain RAG'],
]

interface Message { role: 'user' | 'ai'; content: string }
const QUICK = ['Why did expenses increase?', 'Predict next quarter revenue', 'Explain financial health', 'Detect risks', 'Generate executive summary']

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'ai', content: 'Hi, I am your AI CFO assistant with full visibility into your financial data — 12 months of transactions, forecasts, and anomaly reports.\n\nAsk me anything about your business performance.' }
  ])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])

  const send = async (msg?: string) => {
    const text = msg || input.trim()
    if (!text || loading) return
    setInput('')
    setMessages(prev => [...prev, { role: 'user', content: text }])
    setLoading(true)
    await new Promise(r => setTimeout(r, 1200))
    const lower = text.toLowerCase()
    const match = AI_RESPONSES.find(([k]) => lower.includes(k))
    const response = match ? match[1] : 'I have analyzed your query. Your financial trajectory is positive with a Health Score of 87/100. Revenue growth: +18.4% YoY. Cash runway: 18.4 months. Ask me about expenses, forecasts, anomalies, or reports for specific analysis.'
    setMessages(prev => [...prev, { role: 'ai', content: response }])
    setLoading(false)
  }

  return (
    <div className="flex flex-col" style={{ height: 'calc(100vh - 0px)' }}>
      <DashboardHeader title="AI Financial Assistant" subtitle="Powered by LangChain + RAG" actions={
        <div className="flex items-center gap-2 text-xs text-emerald-400 font-mono">
          <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />AI ONLINE
        </div>
      }/>
      <div className="flex flex-wrap gap-2 px-6 py-2 border-b border-[#1e2d4a]">
        {QUICK.map(q => (
          <button key={q} onClick={() => send(q)} className="text-xs px-3 py-1 rounded-lg border border-[#1e2d4a] bg-[#0d1425] text-gray-400 hover:border-cyan-400/50 hover:text-cyan-400 transition-all">{q}</button>
        ))}
      </div>
      <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-4">
        {messages.map((m, i) => (
          <div key={i} className={`flex gap-3 max-w-3xl ${m.role === 'user' ? 'flex-row-reverse ml-auto' : ''}`}>
            <div className={`w-8 h-8 rounded-xl flex items-center justify-center text-xs font-bold flex-shrink-0 ${m.role === 'ai' ? 'bg-gradient-to-br from-cyan-400 to-blue-500 text-black' : 'bg-[#0d1425] border border-[#1e2d4a] text-gray-300'}`}>
              {m.role === 'ai' ? 'FF' : 'U'}
            </div>
            <div className={`glass-card px-4 py-3 text-xs leading-7 whitespace-pre-wrap ${m.role === 'user' ? 'bg-cyan-400/8 border-cyan-400/20' : ''}`}>
              {m.content}
            </div>
          </div>
        ))}
        {loading && (
          <div className="flex gap-3">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center text-xs font-bold text-black">FF</div>
            <div className="glass-card px-4 py-3 flex gap-1.5 items-center">
              {[0,1,2].map(i => <div key={i} className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-bounce" style={{ animationDelay: i*0.15+'s' }} />)}
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>
      <div className="p-4 border-t border-[#1e2d4a] flex gap-3">
        <textarea value={input} onChange={e => setInput(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() }}}
          placeholder="Ask your AI CFO anything about your finances..."
          className="flex-1 bg-[#0d1425] border border-[#1e2d4a] rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 outline-none resize-none focus:border-cyan-400/50 transition-colors" rows={1} />
        <button onClick={() => send()} disabled={loading}
          className="w-11 h-11 rounded-xl bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center text-black text-lg hover:opacity-90 disabled:opacity-50">→</button>
      </div>
    </div>
  )
}
